#!/bin/bash


##############################################
## Suppression des vignettes personnalisées ##
##############################################


#############
## Version ##
#############
# v0.1 - 2022/01/23 by Terence Belleguic


# Fonction traduisant l'url dans le bon format
function url_encode
{
    # $1 : url du fichier sans file://

    # Si aucune url donnée
    [[ -z "${1}" ]] && return 1

    local LANG=C i Char Thumb

    # Traite les caractères de l'url
    for (( i = 0; i < ${#1}; i++ ))
    do
        Char="${1:i:1}"

        # Si c'est un caractère à ne pas modifier
        if [[ "${Char}" == [[:alnum:]-.,_~/:\(\)\&\!@\[\]\'] ]]
        then
            Thumb+="${Char}"

        # S'il faut encoder le caractère
        else
            Thumb+=$(printf '%%%02X' "'${Char}")
        fi
    done

    # Encodage de l'url
    Thumb="$(echo -n "file://${Thumb}" | md5sum)"

    # Renvoie l'url encodée
    echo "${Thumb%%[[:space:]]*}"

    return 0
}


# Fonction d'affichage des erreurs
function ErrorMsg
{
    # $1 : Titre à afficher
    # $2 : Message à afficher

    local Message

    if [[ $(which kdialog) ]]
    then
        kdialog \
            --title "${1}" \
            --icon "remove-link" \
            --error "${2}"
    fi
}


##############################
## Suppression de vignettes ##
##############################

# Vérifie que le fichier de config existe
if ! grep -q '\[icons\]' "${HOME}/.config/keneric.conf"
then
    exit
fi

# Traite la liste des fichiers
for Item in "${@}"
do
    # Si le fichier n'existe pas
    if [[ ! -e "${Item}" ]]
    then
        Message="Thumbnails link remove" "The <b>${Item}</b> file cannot be found!"
        [[ "${LANG}" == fr* ]] && "Suppression des liens des vignettes" "Le fichier <b>${Item}</b> est introuvable !"
        ErrorMsg "${Message}"

        continue
    fi

    # Hash de la vignette
    RealLink=$(readlink -e "${Item}")
    Thumb="$(url_encode "${RealLink}")"

    # Suppression du lien du fichier de config
    sed -i "/${Thumb}=/d" "${HOME}/.config/keneric.conf"
done

# S'il y a le module de suppression des vignettes
if which keneric-remove-thumbnails &>/dev/null
then
    keneric-remove-thumbnails "${@}"
fi

# Message de fin de traitement
Title="Thumbnails link remove"
Text="Removal of the custom thumbnails link completed."

if [[ "${LANG}" == fr* ]]
then
    Title="Suppression des liens des vignettes"
    Text="Suppression des liens des vignettes personnalisées terminée."
fi

kdialog \
    --title "${Title}" \
    --icon "remove-link" \
    --dontagain hizo-service-menus.cfg:KenericDeleteChooseIcon \
    --msgbox "${Text}"
