#!/bin/bash


####################################
## Personnalisation des vignettes ##
####################################


#############
## Version ##
#############
# v0.1 - 2022/01/23 by Terence Belleguic


# Fonction traduisant l'url dans le bon format
function url_encode
{
    # $1 : url du fichier sans file://

    # Si aucune url donnée
    [[ -z "${1}" ]] && return 1

    local LANG=C i Char Thumb

    # Traite les caractères de l'url
    for (( i = 0; i < ${#1}; i++ ))
    do
        Char="${1:i:1}"

        # Si c'est un caractère à ne pas modifier
        if [[ "${Char}" == [[:alnum:]-.,_~/:\(\)\&\!@\[\]\'] ]]
        then
            Thumb+="${Char}"

        # S'il faut encoder le caractère
        else
            Thumb+=$(printf '%%%02X' "'${Char}")
        fi
    done

    # Encodage de l'url
    Thumb="$(echo -n "file://${Thumb}" | md5sum)"

    # Renvoie l'url encodée
    echo "${Thumb%%[[:space:]]*}"

    return 0
}


# Fonction d'affichage des erreurs
function ErrorMsg
{
    # $1 : Titre à afficher
    # $2 : Message à afficher

    local Message

    if [[ $(which kdialog) ]]
    then
        kdialog \
            --title "${1}" \
            --icon "link" \
            --error "${2}"
    fi
}



# Vérifie que le fichier de config existe et que le groupe icon existe
if ! grep -q '\[icons\]' "${HOME}/.config/keneric.conf"
then
    echo "[icons]" >> "${HOME}/.config/keneric.conf"
fi

# Traite la liste des fichiers
for Item in "${@}"
do
    # Si le fichier n'existe pas
    if [[ ! -e "${Item}" ]]
    then
        if [[ "${LANG}" == fr* ]]
        then
            ErrorMsg "Vignette personnalisée" "Le fichier <b>${Item}</b> est introuvable !"
        else
            ErrorMsg "Custom Thumbnail" "The <b>${Item}</b> file cannot be found!"
        fi

        continue
    fi

    # Texte
    if [[ "${LANG}" == fr* ]]
    then
        Title="Choix de l'icône du fichier ${Item##*/}"
    else
        Title="Choice of the icon of the ${Item##*/} file"
    fi

    # Choix de l'icône
    Icon=$(kdialog \
        --title "${Title}" \
        --getopenfilename \
        --multiple \
        --separate-output \
        --icon "tag-add") || continue


    # Hash de la vignette
    RealLink=$(readlink -e "${Item}")
    Thumb="$(url_encode "${RealLink}")"

    # Si une icône personnalisée existe déjà
    if grep -q "${Thumb}=" "${HOME}/.config/keneric.conf"
    then
        # Modification de l'icône personnalisée
        sed -i "/${Thumb}=/ s/.*/${Thumb}=${Icon//\//\\/}/" "${HOME}/.config/keneric.conf"
    else
        # Ajout de l'icône personnalisée dans le fichier de config keneric.conf
        sed -i "/\[icons\]/a ${Thumb}=${Icon}" "${HOME}/.config/keneric.conf"
    fi
done

# S'il y a le module de suppression des vignettes, on le lance pour mettre à jour l'icône
if which keneric-remove-thumbnails &>/dev/null
then
    keneric-remove-thumbnails "${@}"
fi

# Message de fin de traitement
if [[ "${LANG}" == fr* ]]
then
    kdialog \
    --title "Vignette personnalisée" \
    --icon "link" \
    --dontagain hizo-service-menus.cfg:KenericChooseIcon \
    --msgbox "Mise en place de la vignette personnalisée terminée."

else
    kdialog \
    --title "Custom Thumbnails" \
    --icon "link" \
    --dontagain hizo-service-menus.cfg:KenericChooseIcon \
    --msgbox "Custom thumbnail installation complete."
fi
