#!/bin/bash

##############################
## Version 0.1 - 2023/12/02 ##
##############################
# Nom du fichier : avec un code 999, il sera utilisé en dernier recours en cas de vidéo.

# Utilisation de ffmpegthumbnailer pour toutes les types de vidéo

# Si les dépendances ne sont pas bonnes ou qu'il n'y a pas d'image dans le mkv
if Dependencies ffmpegthumbnailer
then
    LogFileMessage "ffmpegthumbnailer used."

    # Extraction d'une image avec ffmpegthumbnailer
    ffmpegthumbnailer -f -t 20 -s 256 -i "${FullName}" -o "${ExportPicture}" 2>> "${LogRedirection}"

    # Si une vignette a été créée, on stoppe le script
    exit 0
fi
